namespace OpenLocoTool.Headers
{
	enum Colour : uint8_t
	{
		black = 0,
		grey = 1,
		white = 2,
		mutedDarkPurple = 3,
		mutedPurple = 4,
		purple = 5,
		darkBlue = 6,
		blue = 7,
		mutedDarkTeal = 8,
		mutedTeal = 9,
		darkGreen = 10,
		mutedSeaGreen = 11,
		mutedGrassGreen = 12,
		green = 13,
		mutedAvocadoGreen = 14,
		mutedOliveGreen = 15,
		yellow = 16,
		darkYellow = 17,
		orange = 18,
		amber = 19,
		darkOrange = 20,
		mutedDarkYellow = 21,
		mutedYellow = 22,
		brown = 23,
		mutedOrange = 24,
		mutedDarkRed = 25,
		darkRed = 26,
		red = 27,
		darkPink = 28,
		pink = 29,
		mutedRed = 30,
		max,
	};
}
