// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Definitions.Database;

#nullable disable

namespace Definitions.Database.Migrations
{
    [DbContext(typeof(LocoDbContext))]
    [Migration("20250630043418_SubObjectTPT")]
    partial class SubObjectTPT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<ulong>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<ulong>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<ulong>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<ulong>", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<ulong>", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Definitions.Database.TblAuthor", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Definitions.Database.TblDatObject", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("DatChecksum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("xxHash3")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId");

                    b.HasIndex("xxHash3")
                        .IsUnique();

                    b.HasIndex("DatName", "DatChecksum")
                        .IsUnique()
                        .IsDescending(true, false);

                    b.ToTable("DatObjects");
                });

            modelBuilder.Entity("Definitions.Database.TblLicence", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Licences");
                });

            modelBuilder.Entity("Definitions.Database.TblObject", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("LicenceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectSource")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ObjectType")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("UploadedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime(datetime('now', 'localtime'), 'utc')");

                    b.Property<byte?>("VehicleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LicenceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Objects");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectPack", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("LicenceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("UploadedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime(datetime('now', 'localtime'), 'utc')");

                    b.HasKey("Id");

                    b.HasIndex("LicenceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ObjectPacks");
                });

            modelBuilder.Entity("Definitions.Database.TblSC5File", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("LicenceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectSource")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("UploadedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime(datetime('now', 'localtime'), 'utc')");

                    b.HasKey("Id");

                    b.HasIndex("LicenceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SC5Files");
                });

            modelBuilder.Entity("Definitions.Database.TblSC5FilePack", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("LicenceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("UploadedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime(datetime('now', 'localtime'), 'utc')");

                    b.HasKey("Id");

                    b.HasIndex("LicenceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SC5FilePacks");
                });

            modelBuilder.Entity("Definitions.Database.TblStringTableRow", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId");

                    b.HasIndex("Text");

                    b.ToTable("StringTable");
                });

            modelBuilder.Entity("Definitions.Database.TblTag", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Definitions.Database.TblUser", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("AssociatedAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedAuthorId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Definitions.Database.TblUserRole", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("TblAuthorTblObject", b =>
                {
                    b.Property<ulong>("AuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ObjectsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsId", "ObjectsId");

                    b.HasIndex("ObjectsId");

                    b.ToTable("TblAuthorTblObject");
                });

            modelBuilder.Entity("TblAuthorTblObjectPack", b =>
                {
                    b.Property<ulong>("AuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ObjectPacksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsId", "ObjectPacksId");

                    b.HasIndex("ObjectPacksId");

                    b.ToTable("TblAuthorTblObjectPack");
                });

            modelBuilder.Entity("TblAuthorTblSC5File", b =>
                {
                    b.Property<ulong>("AuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SC5FilesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsId", "SC5FilesId");

                    b.HasIndex("SC5FilesId");

                    b.ToTable("TblAuthorTblSC5File");
                });

            modelBuilder.Entity("TblAuthorTblSC5FilePack", b =>
                {
                    b.Property<ulong>("AuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SC5FilePacksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsId", "SC5FilePacksId");

                    b.HasIndex("SC5FilePacksId");

                    b.ToTable("TblAuthorTblSC5FilePack");
                });

            modelBuilder.Entity("TblObjectPackTblTag", b =>
                {
                    b.Property<ulong>("ObjectPacksId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ObjectPacksId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TblObjectPackTblTag");
                });

            modelBuilder.Entity("TblObjectTblObjectPack", b =>
                {
                    b.Property<ulong>("ObjectPacksId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ObjectsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ObjectPacksId", "ObjectsId");

                    b.HasIndex("ObjectsId");

                    b.ToTable("TblObjectTblObjectPack");
                });

            modelBuilder.Entity("TblObjectTblTag", b =>
                {
                    b.Property<ulong>("ObjectsId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ObjectsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TblObjectTblTag");
                });

            modelBuilder.Entity("TblSC5FilePackTblTag", b =>
                {
                    b.Property<ulong>("SC5FilePacksId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SC5FilePacksId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TblSC5FilePackTblTag");
                });

            modelBuilder.Entity("TblSC5FileTblSC5FilePack", b =>
                {
                    b.Property<ulong>("SC5FilePacksId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SC5FilesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SC5FilePacksId", "SC5FilesId");

                    b.HasIndex("SC5FilesId");

                    b.ToTable("TblSC5FileTblSC5FilePack");
                });

            modelBuilder.Entity("TblSC5FileTblTag", b =>
                {
                    b.Property<ulong>("SC5FilesId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SC5FilesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TblSC5FileTblTag");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectAirport", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjAirport");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectBridge", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjBridge");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectBuilding", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjBuilding");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCargo", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjCargo");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCliffEdge", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjCliffEdge");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectClimate", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjClimate");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCompetitor", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjCompetitor");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCurrency", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjCurrency");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectDock", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjDock");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectHillShapes", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjHillShapes");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectIndustry", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjIndustry");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectInterface", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjInterface");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectLand", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjLand");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectLevelCrossing", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjLevelCrossing");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRegion", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjRegion");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRoad", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjRoad");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRoadExtra", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjRoadExtra");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRoadStation", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjRoadStation");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectScaffolding", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjScaffolding");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectScenarioText", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjScenarioText");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectSnow", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjSnow");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectSound", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjSound");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectSteam", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjSteam");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectStreetLight", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjStreetLight");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTownNames", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjTownNames");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrack", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjTrack");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrackExtra", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjTrackExtra");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrackSignal", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjTrackSignal");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrackStation", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjTrackStation");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTree", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjTree");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTunnel", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjTunnel");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectVehicle", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjVehicle");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectWall", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjWall");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectWater", b =>
                {
                    b.HasBaseType("Definitions.Database.TblObject");

                    b.ToTable("ObjWater");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<ulong>", b =>
                {
                    b.HasOne("Definitions.Database.TblUserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<ulong>", b =>
                {
                    b.HasOne("Definitions.Database.TblUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<ulong>", b =>
                {
                    b.HasOne("Definitions.Database.TblUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<ulong>", b =>
                {
                    b.HasOne("Definitions.Database.TblUserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<ulong>", b =>
                {
                    b.HasOne("Definitions.Database.TblUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblDatObject", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Object")
                        .WithMany("DatObjects")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Object");
                });

            modelBuilder.Entity("Definitions.Database.TblObject", b =>
                {
                    b.HasOne("Definitions.Database.TblLicence", "Licence")
                        .WithMany()
                        .HasForeignKey("LicenceId");

                    b.Navigation("Licence");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectPack", b =>
                {
                    b.HasOne("Definitions.Database.TblLicence", "Licence")
                        .WithMany()
                        .HasForeignKey("LicenceId");

                    b.Navigation("Licence");
                });

            modelBuilder.Entity("Definitions.Database.TblSC5File", b =>
                {
                    b.HasOne("Definitions.Database.TblLicence", "Licence")
                        .WithMany()
                        .HasForeignKey("LicenceId");

                    b.Navigation("Licence");
                });

            modelBuilder.Entity("Definitions.Database.TblSC5FilePack", b =>
                {
                    b.HasOne("Definitions.Database.TblLicence", "Licence")
                        .WithMany()
                        .HasForeignKey("LicenceId");

                    b.Navigation("Licence");
                });

            modelBuilder.Entity("Definitions.Database.TblStringTableRow", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Object")
                        .WithMany("StringTable")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Object");
                });

            modelBuilder.Entity("Definitions.Database.TblUser", b =>
                {
                    b.HasOne("Definitions.Database.TblAuthor", "AssociatedAuthor")
                        .WithMany()
                        .HasForeignKey("AssociatedAuthorId");

                    b.Navigation("AssociatedAuthor");
                });

            modelBuilder.Entity("TblAuthorTblObject", b =>
                {
                    b.HasOne("Definitions.Database.TblAuthor", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithMany()
                        .HasForeignKey("ObjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblAuthorTblObjectPack", b =>
                {
                    b.HasOne("Definitions.Database.TblAuthor", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblObjectPack", null)
                        .WithMany()
                        .HasForeignKey("ObjectPacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblAuthorTblSC5File", b =>
                {
                    b.HasOne("Definitions.Database.TblAuthor", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblSC5File", null)
                        .WithMany()
                        .HasForeignKey("SC5FilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblAuthorTblSC5FilePack", b =>
                {
                    b.HasOne("Definitions.Database.TblAuthor", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblSC5FilePack", null)
                        .WithMany()
                        .HasForeignKey("SC5FilePacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblObjectPackTblTag", b =>
                {
                    b.HasOne("Definitions.Database.TblObjectPack", null)
                        .WithMany()
                        .HasForeignKey("ObjectPacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblObjectTblObjectPack", b =>
                {
                    b.HasOne("Definitions.Database.TblObjectPack", null)
                        .WithMany()
                        .HasForeignKey("ObjectPacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithMany()
                        .HasForeignKey("ObjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblObjectTblTag", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithMany()
                        .HasForeignKey("ObjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblSC5FilePackTblTag", b =>
                {
                    b.HasOne("Definitions.Database.TblSC5FilePack", null)
                        .WithMany()
                        .HasForeignKey("SC5FilePacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblSC5FileTblSC5FilePack", b =>
                {
                    b.HasOne("Definitions.Database.TblSC5FilePack", null)
                        .WithMany()
                        .HasForeignKey("SC5FilePacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblSC5File", null)
                        .WithMany()
                        .HasForeignKey("SC5FilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblSC5FileTblTag", b =>
                {
                    b.HasOne("Definitions.Database.TblSC5File", null)
                        .WithMany()
                        .HasForeignKey("SC5FilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectAirport", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectAirport", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectBridge", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectBridge", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectBuilding", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectBuilding", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCargo", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectCargo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCliffEdge", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectCliffEdge", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectClimate", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectClimate", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCompetitor", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectCompetitor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCurrency", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectCurrency", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectDock", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectDock", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectHillShapes", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectHillShapes", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectIndustry", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectIndustry", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectInterface", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectInterface", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectLand", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectLand", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectLevelCrossing", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectLevelCrossing", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRegion", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectRegion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRoad", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectRoad", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRoadExtra", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectRoadExtra", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRoadStation", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectRoadStation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectScaffolding", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectScaffolding", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectScenarioText", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectScenarioText", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectSnow", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectSnow", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectSound", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectSound", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectSteam", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectSteam", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectStreetLight", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectStreetLight", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTownNames", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectTownNames", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrack", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectTrack", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrackExtra", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectTrackExtra", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrackSignal", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectTrackSignal", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrackStation", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectTrackStation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTree", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectTree", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTunnel", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectTunnel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectVehicle", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectVehicle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectWall", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectWall", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObjectWater", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithOne()
                        .HasForeignKey("Definitions.Database.TblObjectWater", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObject", b =>
                {
                    b.Navigation("DatObjects");

                    b.Navigation("StringTable");
                });
#pragma warning restore 612, 618
        }
    }
}
