// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Definitions.Database;

#nullable disable

namespace Definitions.Database.Migrations
{
    [DbContext(typeof(LocoDbContext))]
    [Migration("20250702021058_SubObjectUpdates")]
    partial class SubObjectUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<ulong>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<ulong>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<ulong>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<ulong>", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<ulong>", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Definitions.Database.TblAuthor", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Definitions.Database.TblDatObject", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("DatChecksum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("xxHash3")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId");

                    b.HasIndex("xxHash3")
                        .IsUnique();

                    b.HasIndex("DatName", "DatChecksum")
                        .IsUnique()
                        .IsDescending(true, false);

                    b.ToTable("DatObjects");
                });

            modelBuilder.Entity("Definitions.Database.TblLicence", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Licences");
                });

            modelBuilder.Entity("Definitions.Database.TblObject", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("LicenceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectSource")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ObjectType")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SubObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("UploadedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime(datetime('now', 'localtime'), 'utc')");

                    b.Property<byte?>("VehicleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LicenceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectAirport", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("AllowedPlaneTypes")
                        .HasColumnType("INTEGER");

                    b.Property<short>("BuildCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("DesignedYear")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("LargeTiles")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("MaxX")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("MaxY")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("MinX")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("MinY")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("ObsoleteYear")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SellCostFactor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjAirport");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectBridge", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("BaseCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("ClearHeight")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<short>("DeckDepth")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("DesignedYear")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("DisabledTrackFlags")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<short>("HeightCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MaxHeight")
                        .HasColumnType("INTEGER");

                    b.Property<short>("MaxSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PillarSpacing")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SellCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SpanLength")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjBridge");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectBuilding", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AverageNumberOnMap")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Colours")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<short>("DemolishRatingReduction")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("DesignedYear")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("GeneratorFunction")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("ObsoleteYear")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ScaffoldingColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ScaffoldingSegmentType")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("SellCostFactor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjBuilding");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCargo", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("CargoCategory")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("CargoTransferTime")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MaxNonPremiumDays")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("MaxPremiumRate")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("NumPlatformVariations")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("PaymentFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PaymentIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("PenaltyRate")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PremiumDays")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("StationCargoDensity")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("UnitSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjCargo");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCliffEdge", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjCliffEdge");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectClimate", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FirstSeason")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SeasonLength1")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SeasonLength2")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SeasonLength3")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SeasonLength4")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SummerSnowLine")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("WinterSnowLine")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjClimate");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCompetitor", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Aggressiveness")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AvailableNamePrefixes")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AvailablePlaystyles")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Competitiveness")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Emotions")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjCompetitor");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCurrency", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Factor")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Separator")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjCurrency");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectDock", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("BoatPositionX")
                        .HasColumnType("INTEGER");

                    b.Property<short>("BoatPositionY")
                        .HasColumnType("INTEGER");

                    b.Property<short>("BuildCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("DesignedYear")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("NumBuildingPartAnimations")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("NumBuildingVariationParts")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("ObsoleteYear")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SellCostFactor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjDock");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectHillShapes", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("HillHeightMapCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MountainHeightMapCount")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjHillShapes");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectIndustry", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("BuildCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("BuildingSizeFlags")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Colours")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("DesignedYear")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FarmGrowthStageWithNoProduction")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FarmIdealSize")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("FarmImagesPerGrowthStage")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FarmNumStagesOfGrowth")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FarmTileNumImageAngles")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MapColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MaxNumBuildings")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MinNumBuildings")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MonthlyClosureChance")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("ObsoleteYear")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ScaffoldingColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ScaffoldingSegmentType")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SellCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TotalOfTypeInScenario")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjIndustry");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectInterface", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Colour_11")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ErrorColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MapTooltipCargoColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MapTooltipObjectColour")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PlayerInfoToolbarColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TimeToolbarColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TooltipColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TopToolbarPrimaryColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TopToolbarQuaternaryColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TopToolbarSecondaryColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TopToolbarTertiaryColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("WindowColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("WindowConstructionColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("WindowMapColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("WindowOptionsColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("WindowPlayerColor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("WindowTerraFormColour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("WindowTitlebarColour")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjInterface");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectLand", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("CostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DistributionPattern")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("NumGrowthStages")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("NumImageAngles")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("NumImagesPerGrowthStage")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("NumVariations")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("VariationLikelihood")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjLand");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectLevelCrossing", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AnimationSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ClosedFrames")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ClosingFrames")
                        .HasColumnType("INTEGER");

                    b.Property<short>("CostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("DesignedYear")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SellCostFactor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjLevelCrossing");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectPack", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("LicenceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("UploadedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime(datetime('now', 'localtime'), 'utc')");

                    b.HasKey("Id");

                    b.HasIndex("LicenceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ObjectPacks");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRegion", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjRegion");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRoad", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("BuildCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DisplayOffset")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<short>("MaxSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PaintStyle")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("RoadPieces")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SellCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TargetTownSize")
                        .HasColumnType("INTEGER");

                    b.Property<short>("TunnelCostFactor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjRoad");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRoadExtra", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("BuildCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PaintStyle")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("RoadPieces")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SellCostFactor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjRoadExtra");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRoadStation", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("BuildCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CompatibleRoadObjectCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("DesignedYear")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("ObsoleteYear")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PaintStyle")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("RoadPieces")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SellCostFactor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjRoadStation");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectScaffolding", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjScaffolding");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectScenarioText", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjScenarioText");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectSnow", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjSnow");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectSound", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ShouldLoop")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjSound");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectSteam", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("NumStationaryTicks")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SpriteHeightNegative")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SpriteHeightPositive")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SpriteWidth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjSteam");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectStreetLight", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjStreetLight");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTownNames", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjTownNames");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrack", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("BuildCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<short>("CurveSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DisplayOffset")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SellCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("StationTrackPieces")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("TrackPieces")
                        .HasColumnType("INTEGER");

                    b.Property<short>("TunnelCostFactor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjTrack");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrackExtra", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("BuildCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PaintStyle")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SellCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("TrackPieces")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjTrackExtra");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrackSignal", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AnimationSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<short>("BuildCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("DesignedYear")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("NumFrames")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("ObsoleteYear")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SellCostFactor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjTrackSignal");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrackStation", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("BuildCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("DesignedYear")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("ObsoleteYear")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PaintStyle")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SellCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("TrackPieces")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjTrackStation");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTree", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("BuildCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ClearCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Clearance")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Colours")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<short>("DemolishRatingReduction")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("NumGrowthStages")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("NumRotations")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SeasonState")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("ShadowImageOffset")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjTree");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTunnel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjTunnel");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectVehicle", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("CostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("DesignedYear")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DrivingSoundType")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("NumCarComponents")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("NumCompatibleVehicles")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("NumRequiredTrackExtras")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("ObsoleteYear")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RackSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Reliability")
                        .HasColumnType("INTEGER");

                    b.Property<short>("RunCostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("RunCostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ShipWakeOffset")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("TrackTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjVehicle");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectWall", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Flags1")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjWall");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectWater", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("CostFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("CostIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ObjWater");
                });

            modelBuilder.Entity("Definitions.Database.TblSC5File", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("LicenceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectSource")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("UploadedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime(datetime('now', 'localtime'), 'utc')");

                    b.HasKey("Id");

                    b.HasIndex("LicenceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SC5Files");
                });

            modelBuilder.Entity("Definitions.Database.TblSC5FilePack", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("LicenceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("UploadedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime(datetime('now', 'localtime'), 'utc')");

                    b.HasKey("Id");

                    b.HasIndex("LicenceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SC5FilePacks");
                });

            modelBuilder.Entity("Definitions.Database.TblStringTableRow", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId");

                    b.HasIndex("Text");

                    b.ToTable("StringTable");
                });

            modelBuilder.Entity("Definitions.Database.TblTag", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Definitions.Database.TblUser", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("AssociatedAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedAuthorId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Definitions.Database.TblUserRole", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("TblAuthorTblObject", b =>
                {
                    b.Property<ulong>("AuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ObjectsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsId", "ObjectsId");

                    b.HasIndex("ObjectsId");

                    b.ToTable("TblAuthorTblObject");
                });

            modelBuilder.Entity("TblAuthorTblObjectPack", b =>
                {
                    b.Property<ulong>("AuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ObjectPacksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsId", "ObjectPacksId");

                    b.HasIndex("ObjectPacksId");

                    b.ToTable("TblAuthorTblObjectPack");
                });

            modelBuilder.Entity("TblAuthorTblSC5File", b =>
                {
                    b.Property<ulong>("AuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SC5FilesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsId", "SC5FilesId");

                    b.HasIndex("SC5FilesId");

                    b.ToTable("TblAuthorTblSC5File");
                });

            modelBuilder.Entity("TblAuthorTblSC5FilePack", b =>
                {
                    b.Property<ulong>("AuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SC5FilePacksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorsId", "SC5FilePacksId");

                    b.HasIndex("SC5FilePacksId");

                    b.ToTable("TblAuthorTblSC5FilePack");
                });

            modelBuilder.Entity("TblObjectPackTblTag", b =>
                {
                    b.Property<ulong>("ObjectPacksId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ObjectPacksId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TblObjectPackTblTag");
                });

            modelBuilder.Entity("TblObjectTblObjectPack", b =>
                {
                    b.Property<ulong>("ObjectPacksId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ObjectsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ObjectPacksId", "ObjectsId");

                    b.HasIndex("ObjectsId");

                    b.ToTable("TblObjectTblObjectPack");
                });

            modelBuilder.Entity("TblObjectTblTag", b =>
                {
                    b.Property<ulong>("ObjectsId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ObjectsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TblObjectTblTag");
                });

            modelBuilder.Entity("TblSC5FilePackTblTag", b =>
                {
                    b.Property<ulong>("SC5FilePacksId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SC5FilePacksId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TblSC5FilePackTblTag");
                });

            modelBuilder.Entity("TblSC5FileTblSC5FilePack", b =>
                {
                    b.Property<ulong>("SC5FilePacksId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SC5FilesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SC5FilePacksId", "SC5FilesId");

                    b.HasIndex("SC5FilesId");

                    b.ToTable("TblSC5FileTblSC5FilePack");
                });

            modelBuilder.Entity("TblSC5FileTblTag", b =>
                {
                    b.Property<ulong>("SC5FilesId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SC5FilesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TblSC5FileTblTag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<ulong>", b =>
                {
                    b.HasOne("Definitions.Database.TblUserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<ulong>", b =>
                {
                    b.HasOne("Definitions.Database.TblUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<ulong>", b =>
                {
                    b.HasOne("Definitions.Database.TblUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<ulong>", b =>
                {
                    b.HasOne("Definitions.Database.TblUserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<ulong>", b =>
                {
                    b.HasOne("Definitions.Database.TblUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblDatObject", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Object")
                        .WithMany("DatObjects")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Object");
                });

            modelBuilder.Entity("Definitions.Database.TblObject", b =>
                {
                    b.HasOne("Definitions.Database.TblLicence", "Licence")
                        .WithMany()
                        .HasForeignKey("LicenceId");

                    b.Navigation("Licence");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectAirport", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectBridge", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectBuilding", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCargo", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCliffEdge", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectClimate", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCompetitor", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectCurrency", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectDock", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectHillShapes", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectIndustry", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectInterface", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectLand", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectLevelCrossing", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectPack", b =>
                {
                    b.HasOne("Definitions.Database.TblLicence", "Licence")
                        .WithMany()
                        .HasForeignKey("LicenceId");

                    b.Navigation("Licence");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRegion", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRoad", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRoadExtra", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectRoadStation", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectScaffolding", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectScenarioText", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectSnow", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectSound", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectSteam", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectStreetLight", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTownNames", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrack", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrackExtra", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrackSignal", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTrackStation", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTree", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectTunnel", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectVehicle", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectWall", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblObjectWater", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Definitions.Database.TblSC5File", b =>
                {
                    b.HasOne("Definitions.Database.TblLicence", "Licence")
                        .WithMany()
                        .HasForeignKey("LicenceId");

                    b.Navigation("Licence");
                });

            modelBuilder.Entity("Definitions.Database.TblSC5FilePack", b =>
                {
                    b.HasOne("Definitions.Database.TblLicence", "Licence")
                        .WithMany()
                        .HasForeignKey("LicenceId");

                    b.Navigation("Licence");
                });

            modelBuilder.Entity("Definitions.Database.TblStringTableRow", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", "Object")
                        .WithMany("StringTable")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Object");
                });

            modelBuilder.Entity("Definitions.Database.TblUser", b =>
                {
                    b.HasOne("Definitions.Database.TblAuthor", "AssociatedAuthor")
                        .WithMany()
                        .HasForeignKey("AssociatedAuthorId");

                    b.Navigation("AssociatedAuthor");
                });

            modelBuilder.Entity("TblAuthorTblObject", b =>
                {
                    b.HasOne("Definitions.Database.TblAuthor", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithMany()
                        .HasForeignKey("ObjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblAuthorTblObjectPack", b =>
                {
                    b.HasOne("Definitions.Database.TblAuthor", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblObjectPack", null)
                        .WithMany()
                        .HasForeignKey("ObjectPacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblAuthorTblSC5File", b =>
                {
                    b.HasOne("Definitions.Database.TblAuthor", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblSC5File", null)
                        .WithMany()
                        .HasForeignKey("SC5FilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblAuthorTblSC5FilePack", b =>
                {
                    b.HasOne("Definitions.Database.TblAuthor", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblSC5FilePack", null)
                        .WithMany()
                        .HasForeignKey("SC5FilePacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblObjectPackTblTag", b =>
                {
                    b.HasOne("Definitions.Database.TblObjectPack", null)
                        .WithMany()
                        .HasForeignKey("ObjectPacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblObjectTblObjectPack", b =>
                {
                    b.HasOne("Definitions.Database.TblObjectPack", null)
                        .WithMany()
                        .HasForeignKey("ObjectPacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithMany()
                        .HasForeignKey("ObjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblObjectTblTag", b =>
                {
                    b.HasOne("Definitions.Database.TblObject", null)
                        .WithMany()
                        .HasForeignKey("ObjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblSC5FilePackTblTag", b =>
                {
                    b.HasOne("Definitions.Database.TblSC5FilePack", null)
                        .WithMany()
                        .HasForeignKey("SC5FilePacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblSC5FileTblSC5FilePack", b =>
                {
                    b.HasOne("Definitions.Database.TblSC5FilePack", null)
                        .WithMany()
                        .HasForeignKey("SC5FilePacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblSC5File", null)
                        .WithMany()
                        .HasForeignKey("SC5FilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblSC5FileTblTag", b =>
                {
                    b.HasOne("Definitions.Database.TblSC5File", null)
                        .WithMany()
                        .HasForeignKey("SC5FilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Definitions.Database.TblTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Definitions.Database.TblObject", b =>
                {
                    b.Navigation("DatObjects");

                    b.Navigation("StringTable");
                });
#pragma warning restore 612, 618
        }
    }
}
