using Definitions.Database;

namespace Definitions.DTO.Mappers;

public static class DtoObjectVehicleMapper
{
	public static DtoObjectVehicle ToDto(this TblObjectVehicle tblobjectvehicle) => new()
	{
		Mode = tblobjectvehicle.Mode,
		Type = tblobjectvehicle.Type,
		NumCarComponents = tblobjectvehicle.NumCarComponents,
		RoadOrTrackType = tblobjectvehicle.RoadOrTrackType,
		TrackTypeId = tblobjectvehicle.TrackTypeId,
		CostIndex = tblobjectvehicle.CostIndex,
		CostFactor = tblobjectvehicle.CostFactor,
		Reliability = tblobjectvehicle.Reliability,
		RunCostIndex = tblobjectvehicle.RunCostIndex,
		RunCostFactor = tblobjectvehicle.RunCostFactor,
		CompanyColourSchemeIndex = tblobjectvehicle.CompanyColourSchemeIndex,
		CompatibleVehicles = tblobjectvehicle.CompatibleVehicles,
		RequiredTrackExtras = tblobjectvehicle.RequiredTrackExtras,
		CarComponents = tblobjectvehicle.CarComponents,
		BodySprites = tblobjectvehicle.BodySprites,
		BogieSprites = tblobjectvehicle.BogieSprites,
		Power = tblobjectvehicle.Power,
		Speed = tblobjectvehicle.Speed,
		RackSpeed = tblobjectvehicle.RackSpeed,
		Weight = tblobjectvehicle.Weight,
		Flags = tblobjectvehicle.Flags,
		MaxCargo = tblobjectvehicle.MaxCargo,
		CompatibleCargoCategories = tblobjectvehicle.CompatibleCargoCategories,
		CargoTypeSpriteOffsets = tblobjectvehicle.CargoTypeSpriteOffsets,
		NumSimultaneousCargoTypes = tblobjectvehicle.NumSimultaneousCargoTypes,
		ParticleEmitters = tblobjectvehicle.ParticleEmitters,
		ShipWakeSpacing = tblobjectvehicle.ShipWakeSpacing,
		DesignedYear = tblobjectvehicle.DesignedYear,
		ObsoleteYear = tblobjectvehicle.ObsoleteYear,
		RackRail = tblobjectvehicle.RackRail,
		DrivingSoundType = tblobjectvehicle.DrivingSoundType,
		FrictionSound = tblobjectvehicle.FrictionSound,
		SimpleMotorSound = tblobjectvehicle.SimpleMotorSound,
		GearboxMotorSound = tblobjectvehicle.GearboxMotorSound,
		DrivingSound = tblobjectvehicle.DrivingSound,
		StartSounds = tblobjectvehicle.StartSounds,
		CrossingSounds = tblobjectvehicle.CrossingSounds,
		Id = tblobjectvehicle.Id,
	};

	public static TblObjectVehicle ToTblObjectVehicleEntity(this DtoObjectVehicle model, TblObject parent) => new()
	{
		Parent = parent,
		Mode = model.Mode,
		Type = model.Type,
		NumCarComponents = model.NumCarComponents,
		RoadOrTrackType = model.RoadOrTrackType,
		TrackTypeId = model.TrackTypeId,
		CostIndex = model.CostIndex,
		CostFactor = model.CostFactor,
		Reliability = model.Reliability,
		RunCostIndex = model.RunCostIndex,
		RunCostFactor = model.RunCostFactor,
		CompanyColourSchemeIndex = model.CompanyColourSchemeIndex,
		CompatibleVehicles = model.CompatibleVehicles,
		RequiredTrackExtras = model.RequiredTrackExtras,
		CarComponents = model.CarComponents,
		BodySprites = model.BodySprites,
		BogieSprites = model.BogieSprites,
		Power = model.Power,
		Speed = model.Speed,
		RackSpeed = model.RackSpeed,
		Weight = model.Weight,
		Flags = model.Flags,
		MaxCargo = model.MaxCargo,
		CompatibleCargoCategories = model.CompatibleCargoCategories,
		CargoTypeSpriteOffsets = model.CargoTypeSpriteOffsets,
		NumSimultaneousCargoTypes = model.NumSimultaneousCargoTypes,
		ParticleEmitters = model.ParticleEmitters,
		ShipWakeSpacing = model.ShipWakeSpacing,
		DesignedYear = model.DesignedYear,
		ObsoleteYear = model.ObsoleteYear,
		RackRail = model.RackRail,
		DrivingSoundType = model.DrivingSoundType,
		FrictionSound = model.FrictionSound,
		SimpleMotorSound = model.SimpleMotorSound,
		GearboxMotorSound = model.GearboxMotorSound,
		DrivingSound = model.DrivingSound,
		StartSounds = model.StartSounds,
		CrossingSounds = model.CrossingSounds,
		Id = model.Id,
	};

}

