using Index;
using System.Threading.Channels;

namespace ObjectService.Services;

/// <summary>
/// Single shared gate that serialises file operations across all folder watchers, so the object
/// index and the SQLite database are never written by two folders at the same time. Drops are
/// infrequent so a single lock keeps the concurrency reasoning trivial.
/// </summary>
public sealed class GameDataWatcherLock
{
	public SemaphoreSlim Semaphore { get; } = new(1, 1);
}

/// <summary>A single file event raised by a folder's <see cref="FileSystemWatcher"/>.</summary>
public readonly record struct GameDataWorkItem(string Path, bool IsRemoval);

/// <summary>
/// <para>
/// Base class for the seven per-folder watchers. It owns all of the common machinery - the
/// <see cref="FileSystemWatcher"/>, the event channel, coalescing/queueing, waiting for a file to
/// finish being copied in, rename and delete handling, filtering out server-generated/temp files,
/// the shared serialization lock, reconciliation dispatch, logging and disposal.
/// </para>
/// <para>
/// Concrete subclasses are therefore tiny: they supply the folder and resolve their own
/// entity-specific service (see <see cref="IGameDataFileService"/>), where all of the
/// folder-specific behaviour lives.
/// </para>
/// </summary>
public abstract class GameDataFolderWatcher : IDisposable
{
	private const int SettleAttempts = 12;
	private const int SettleDelayMs = 250;

	// Files generated by the server itself must never trigger another watcher pass.
	private static readonly string[] IgnoredFileNames =
	[
		ObjectIndex.DefaultIndexFileName,
		ObjectIndex.DefaultIndexDbFileName,
	];

	// Typical in-progress download / temp file extensions.
	private static readonly string[] IgnoredExtensions =
	[
		".tmp", ".temp", ".part", ".partial", ".crdownload", ".db-journal", ".db-wal", ".db-shm",
	];

	private readonly IServiceScopeFactory _scopeFactory;
	private readonly GameDataWatcherLock _operationLock;
	private readonly Channel<GameDataWorkItem> _pending = Channel.CreateUnbounded<GameDataWorkItem>(new UnboundedChannelOptions
	{
		SingleReader = true,
		SingleWriter = false,
	});

	private FileSystemWatcher? _watcher;
	private CancellationTokenSource? _cts;
	private Task? _consumer;
	private bool _disposed;

	protected GameDataFolderWatcher(
		string category,
		string folder,
		IServiceScopeFactory scopeFactory,
		ILoggerFactory loggerFactory,
		GameDataWatcherLock operationLock)
	{
		Category = category;
		Folder = folder;
		_scopeFactory = scopeFactory;
		_operationLock = operationLock;
		Logger = loggerFactory.CreateLogger($"GameDataWatcher.{category}");
	}

	/// <summary>Friendly folder name, used only for logging.</summary>
	public string Category { get; }

	/// <summary>The absolute folder this watcher owns.</summary>
	public string Folder { get; }

	protected ILogger Logger { get; }

	/// <summary>
	/// Resolves this folder's entity-specific import service from a new dependency-injection scope.
	/// </summary>
	protected abstract IGameDataFileService ResolveService(IServiceProvider services);

	/// <summary>Starts the OS watcher for this folder and the consumer that processes its events.</summary>
	public void Start()
	{
		if (_watcher != null)
		{
			return;
		}

		_cts = new CancellationTokenSource();

		_watcher = new FileSystemWatcher(Folder)
		{
			IncludeSubdirectories = true,
			NotifyFilter = NotifyFilters.FileName | NotifyFilters.LastWrite | NotifyFilters.Size | NotifyFilters.CreationTime,
			InternalBufferSize = 64 * 1024,
		};

		_watcher.Created += (_, e) => Enqueue(new GameDataWorkItem(e.FullPath, false));
		_watcher.Changed += (_, e) => Enqueue(new GameDataWorkItem(e.FullPath, false));
		_watcher.Deleted += (_, e) => Enqueue(new GameDataWorkItem(e.FullPath, true));
		_watcher.Renamed += (_, e) =>
		{
			// A move is a removal of the old path followed by an import of the new one.
			Enqueue(new GameDataWorkItem(e.OldFullPath, true));
			Enqueue(new GameDataWorkItem(e.FullPath, false));
		};
		_watcher.Error += (_, e) => Logger.LogError(e.GetException(), "{Category} file watcher error; some changes may have been missed", Category);

		_watcher.EnableRaisingEvents = true;
		_consumer = Task.Run(() => ConsumeAsync(_cts.Token));

		Logger.LogInformation("Watching {Category} folder \"{Folder}\"", Category, Folder);
	}

	/// <summary>Stops watching and drains the consumer.</summary>
	public async Task StopAsync()
	{
		if (_watcher != null)
		{
			_watcher.EnableRaisingEvents = false;
		}

		if (_cts != null)
		{
			await _cts.CancelAsync().ConfigureAwait(false);
		}

		_ = _pending.Writer.TryComplete();

		if (_consumer != null)
		{
			try
			{
				await _consumer.ConfigureAwait(false);
			}
			catch (OperationCanceledException)
			{
				// Normal shutdown.
			}
		}
	}

	private async Task ConsumeAsync(CancellationToken ct)
	{
		try
		{
			while (await _pending.Reader.WaitToReadAsync(ct).ConfigureAwait(false))
			{
				while (_pending.Reader.TryRead(out var item))
				{
					await ProcessAsync(item, ct).ConfigureAwait(false);
				}
			}
		}
		catch (OperationCanceledException)
		{
			// Normal shutdown.
		}
	}

	private void Enqueue(GameDataWorkItem item)
	{
		if (IsIgnored(item.Path))
		{
			return;
		}

		_ = _pending.Writer.TryWrite(item);
	}

	private static bool IsIgnored(string path)
	{
		var fileName = Path.GetFileName(path);
		if (string.IsNullOrEmpty(fileName) || fileName.StartsWith('.'))
		{
			return true;
		}

		if (IgnoredFileNames.Contains(fileName, StringComparer.OrdinalIgnoreCase))
		{
			return true;
		}

		var extension = Path.GetExtension(path);
		return IgnoredExtensions.Contains(extension, StringComparer.OrdinalIgnoreCase);
	}

	private async Task ProcessAsync(GameDataWorkItem item, CancellationToken ct)
	{
		if (ct.IsCancellationRequested)
		{
			return;
		}

		try
		{
			await _operationLock.Semaphore.WaitAsync(ct).ConfigureAwait(false);
		}
		catch (OperationCanceledException)
		{
			return;
		}

		try
		{
			using var scope = _scopeFactory.CreateScope();
			var service = ResolveService(scope.ServiceProvider);

			if (item.IsRemoval)
			{
				// A rename raises a removal for the old path; only act if the file is genuinely gone.
				if (File.Exists(item.Path))
				{
					return;
				}

				var removeResult = await service.RemoveAsync(item.Path, ct).ConfigureAwait(false);
				LogResult(removeResult, item.Path);
				return;
			}

			// Wait for a copy-in to finish; a file that vanished (e.g. a short-lived temp file) is
			// simply ignored.
			if (!await WaitForFileReadyAsync(item.Path, ct).ConfigureAwait(false))
			{
				Logger.LogDebug("Ignored \"{Path}\" as it never became available for reading", item.Path);
				return;
			}

			var importResult = await service.ImportAsync(item.Path, ct).ConfigureAwait(false);
			LogResult(importResult, item.Path);
		}
		catch (OperationCanceledException) when (ct.IsCancellationRequested)
		{
			// Normal shutdown.
		}
		catch (Exception ex)
		{
			Logger.LogError(ex, "Failed to process {Category} file \"{Path}\"", Category, item.Path);
		}
		finally
		{
			_ = _operationLock.Semaphore.Release();
		}
	}

	/// <summary>Reassesses this folder using its entity-specific service.</summary>
	public async Task ReconcileAsync(CancellationToken ct)
	{
		using var scope = _scopeFactory.CreateScope();
		var service = ResolveService(scope.ServiceProvider);
		await service.ReconcileAsync(ct).ConfigureAwait(false);
	}

	private void LogResult(GameDataImportResult result, string path)
	{
		if (result.Status is GameDataImportStatus.Failed)
		{
			Logger.LogWarning("{Category} file not processed ({Status}): \"{Path}\" - {Message}", Category, result.Status, path, result.Message);
		}
		else if (result.Status is GameDataImportStatus.Skipped)
		{
			Logger.LogDebug("{Category} file {Status}: \"{Path}\" - {Message}", Category, result.Status, path, result.Message);
		}
		else
		{
			Logger.LogInformation("{Status} {Category} file \"{Path}\": {Message}", result.Status, Category, path, result.Message);
		}
	}

	/// <summary>
	/// Returns <see langword="true"/> once the file exists and can be opened exclusively, which
	/// indicates whatever process created it has finished writing.
	/// </summary>
	private static async Task<bool> WaitForFileReadyAsync(string path, CancellationToken ct)
	{
		for (var attempt = 0; attempt < SettleAttempts; attempt++)
		{
			if (ct.IsCancellationRequested || !File.Exists(path))
			{
				return false;
			}

			try
			{
				using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.None);
				return true;
			}
			catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
			{
				// Still being written/copied, or briefly locked - wait and retry.
			}

			try
			{
				await Task.Delay(SettleDelayMs, ct).ConfigureAwait(false);
			}
			catch (OperationCanceledException)
			{
				return false;
			}
		}

		return false;
	}

	public void Dispose()
	{
		Dispose(disposing: true);
		GC.SuppressFinalize(this);
	}

	protected virtual void Dispose(bool disposing)
	{
		if (_disposed || !disposing)
		{
			return;
		}

		_disposed = true;
		_watcher?.Dispose();
		_cts?.Dispose();
	}
}